config/routes.rb
Rails.application.routes.draw do

  root 'rounds#index'

  get '/index' => 'rounds#index'

  resources :rounds do
    resources :answers
  end

  namespace :admin do
    resources :answers
    resources :rounds
    resources :imdbs
    resources :people
  end
  # mount Fae below your admin namespec
  mount Fae::Engine => '/admin'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/round.rb
class Round < ApplicationRecord
  include Fae::BaseModelConcern

  def fae_display_field
    name
  end

  def percent_correct
    answers.size > 0 ? (correct_count * 100) / answers.size : 0
  end

  def percent_complete
    100 * answers.size / total
  end

  def incorrect_count
    answers.select {|a| a.correct == false}.count
  end

  def correct_count
    answers.select {|a| a.correct == true}.count
  end

  has_many :answers, :dependent => :destroy

end

app/controllers/admin/rounds_controller.rb
module Admin
  class RoundsController < Fae::BaseController

  end
end

app/controllers/rounds_controller.rb
require 'fuzzystringmatch'

class RoundsController < ApplicationController

  @@size = 100

  @@correct_percent = 0.85

  @@jarow = FuzzyStringMatch::JaroWinkler.create( :native )

  def index
    @items = Round.order(id: :desc).all
  end

  def show
    @round = Round.find(params[:id])
    @person = Person.find(@round.quiz.split("&").first)
    @incorrect_list = incorrect_list(@round.incorrect)
  end

  def new
    @round = Round.new
    @round.correct = 0
    @round.answered = 0
    size = params[:size]? params[:size] : @@size
    @round.total = size
    @round.name = "Round #{Round.count+1}"
    # Convert the array of People to an array of id's
    @round.quiz = Person.all.shuffle[0..size-1].map(&:id).join('&')
    @round.save

    redirect_to @round
  end
  
  def update
    #find or create the current round
    @round = Round.find(params[:id])
    person = Person.find(@round.quiz.split("&").first)

    answer = params[:actor_name]
    score = check_answer?(answer, person.name)
    correct = score >= @@correct_percent
    @round.answers.build(answer: answer, correct_answer: person.name, score: score, correct: correct)

    percent = (score * 100).round(2)
    #update the list of incorrect answers
    if correct
      @round.correct += 1
      flash[:correct] = "Correct! (#{percent}%) #{answer} for #{person.name} "
      msg_type = :correct
    else
      # Incorrect is stored as a string concatenation of person ids
      add_incorrect!(@round, person)
      flash_type = params[:skip]? 'Skipped':'Incorrect'
      flash[:incorrect] = "#{flash_type}: (#{percent}%)#{answer} for #{person.name}"
    end

    @round.answered += 1
    @round.save

    if next_person
      redirect_to @round
    else
      redirect_to :index
    end
  end

  def next_person
    return true unless @round.quiz

    quiz = @round.quiz.split("&")

    more = true

    # Delete the current person from the array so the next person will be first on subsequent calls
    if (quiz.second)
      quiz.delete(quiz.first)
      @round.quiz = quiz.join("&")
    else
      quiz.delete(quiz.first)
      more = false
    end
    @round.save

    return more
  end

  def check_answer?(answered, actual)
    match = (normalize_string(answered) == normalize_string(actual))
    match ? 1 : fuzzy_match(answered, actual)
  end

  def fuzzy_match(answered, actual)
    @@jarow.getDistance( answered, actual).round(3)
  end

  private

  def normalize_string(str)
    str.downcase.gsub(/\s+/, "")
  end

  def incorrect_list(str)
    return unless str
    list = []
    ids = str.split("&") 
    ids.each { |person_id|
      list << Person.find(person_id)
    }
    list.sort_by! {|p| p.last_name }
  end

  def add_incorrect!(round, person)
    return unless round && person

    if round.incorrect.nil?
      round.incorrect = person.id
    else
      round.incorrect += "&#{person.id}" if person.id
    end
  end
end

app/views/rounds/index.html.slim
.row.row-1
  .columns
    a href="#{new_round_path}"
      button.button.start-button type="button" New Round

main.content
  table.js-sort-column
    thead
      tr
        th Name
        th Count
        th incorrect
        th Complete %
        th Correct %
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to "#{item.fae_display_field} #{"Completed" if item.answered >= item.total}", round_answers_path(round_id: item.id)
            td = item.total
            td = item.incorrect_count
            td = item.percent_complete
            td = item.percent_correct
            td = fae_date_format item.updated_at
            td = link_to image_tag(asset_path("play.png"),:class => 'play-icon'), item
      - else
        tr: td colspan="6" No rounds found

app/views/rounds/show.html.slim
.row
  .columns.small-2
  .columns.small-4.small-offset-3.medium-2.medium-offset-4
      h4.heading-1
        = link_to "Answers: #{@round.answers.size}", round_answers_path(round_id: @round.id)
  .columns.small-4.medium-2
      h4.heading-1 Score: #{@round.percent_correct}%
  .columns.small-2

.row
  .columns.small-12.column-1
    .rule.rule-2
      hr

    .responsive-picture.picture-2
      picture
        img alt="#{@person.name}" srcset="#{@person.actor_image.asset.url}" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"

.row
  .coumns.small-12
    h2.heading-2 Actor Top Movies...

.row
  .columns.small-12
    .rule.rule-1
      hr

= form_tag(@round, method: :put)
  .row
    .columns.small-12
      h2.heading-2 What is this actor's name?
  .row
    .cloums.small-12
      input.input-2 value="" name="actor_name" type="text" autofocus=""
  .row
    .columns.small-6.column-9
      button.button.left-button type="submit" name="answer" value="#{@person.id}" Answer
    .columns.small-6.column-8
      button.button.right-button type="submit"name="skip" value="#{@person.id}" Skip

.row
  .columns.medium-12.small-12
    .columns.column-1.medium-10.small-10
      - flash.each do |name, msg|
        h2.heading-1 class="#{name}" #{msg}
    .columns.column-11.medium-2.small-2
      a.responsive-picture.picture-link-1 href="#{index_path}"
        picture
          img alt="Home Icon" srcset="#{asset_path('icon-home.png')}" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"

row
  .coumns.small-8.small-offset-2
    h2.heading-2 #{@round.name} (#{@round.id})