config/routes.rb
Rails.application.routes.draw do

  root 'rounds#index'

  get '/index' => 'rounds#index'

  resources :rounds do
    resources :answers
  end

  namespace :admin do
    resources :answers
    resources :rounds
    resources :imdbs
    resources :people
  end
  # mount Fae below your admin namespec
  mount Fae::Engine => '/admin'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Fae::BaseModelConcern

  def fae_display_field
     answer
  end

  def self.for_fae_index
    order(:id)
  end

  belongs_to :round
end

app/controllers/admin/answers_controller.rb
module Admin
  class AnswersController < Fae::BaseController

    def index
      @round = Round.find(params[:round_id]) if params[:round_id]
      @items = @round? @round.answers : Answer.all
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def index
    if params[:round_id]
      @round = Round.find(params[:round_id])
      @items = @round.answers
    else
      @items = Answer.all
      end
  end
  
end

app/views/answers/index.html.slim
.row.row-1
  .columns
    a href="#{round_path(@round.id)}"
      button.button.start-button type="button" Resume Round

main.content
  h3 #{@round.fae_display_field} &nbsp;&nbsp;&nbsp;&nbsp; Answer Count: #{@items.size} &nbsp;&nbsp;&nbsp;Score: #{@round.percent_correct}%
  table.js-sort-column
    thead
      tr
        th #
        th Answer
        th Correct Answer
        th Score
        th Correct
        th.-action-wide Modified

    tbody
      - if @items.present?
        - @items.each_with_index do |item, index|
          tr id=fae_sort_id(item)
            td = index + 1
            - if item.fae_display_field.empty?
              td = 'Skipped'
            - else
              td = item.fae_display_field
            td = item.correct_answer
            td = item.score
            td = item.correct
            td = item.updated_at
      - else
        tr: td colspan="5" No items found