config/routes.rb
Rails.application.routes.draw do

  root 'rounds#index'

  get '/index' => 'rounds#index'

  resources :rounds do
    resources :answers
  end

  namespace :admin do
    resources :answers
    resources :rounds
    resources :imdbs
    resources :people
  end
  # mount Fae below your admin namespec
  mount Fae::Engine => '/admin'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Fae::BaseModelConcern

  def fae_display_field
     answer
  end

  def self.for_fae_index
    order(:id)
  end

  belongs_to :round
end

app/controllers/admin/answers_controller.rb
module Admin
  class AnswersController < Fae::BaseController

    def index
      @round = Round.find(params[:round_id]) if params[:round_id]
      @items = @round? @round.answers : Answer.all
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def index
    if params[:round_id]
      @round = Round.find(params[:round_id])
      @items = @round.answers
    else
      @items = Answer.all
      end
  end
  
end

app/views/admin/answers/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  header.content-header.js-content-header
    == render 'fae/shared/form_header', header: @klass_name
  == render 'fae/shared/errors'

  main.content
    = fae_input f, :answer
    = fae_input f, :correct_answer
    = fae_input f, :score
    = fae_input f, :correct

    = fae_association f, :round

app/views/admin/answers/edit.html.slim
== render 'form'

app/views/admin/answers/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  - if @round
    h3 #{@round.fae_display_field} &nbsp;&nbsp;&nbsp;&nbsp; Answer Count: #{@items.size} &nbsp;&nbsp;&nbsp;Score: #{@round.percent_correct}%
  table.js-sort-column
    thead
      tr
        - unless @round
          th width="10%" Round
        th Answer
        th Correct Answer
        th Score
        th Correct
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            - unless @round
              td = item.round.fae_display_field
            - if item.fae_display_field.empty?
              td = link_to 'Skipped', edit_admin_answer_path(item)
            - else
              td = link_to item.fae_display_field, edit_admin_answer_path(item)
            td = item.correct_answer
            td = item.score
            td = item.correct
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="#{(@round) ? 6 : 7}" No items found

app/views/admin/answers/new.html.slim
== render 'form'