config/routes.rb
Rails.application.routes.draw do

  root 'rounds#index'

  get '/index' => 'rounds#index'

  resources :rounds do
    resources :answers
  end

  namespace :admin do
    resources :answers
    resources :rounds
    resources :imdbs
    resources :people
  end
  # mount Fae below your admin namespec
  mount Fae::Engine => '/admin'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/person.rb
class Person < ApplicationRecord
  include Fae::BaseModelConcern

  def fae_display_field
    name
  end

  has_fae_image :actor_image
  
  belongs_to :imdb

end

app/controllers/admin/people_controller.rb
module Admin
  class PeopleController < Fae::BaseController

    private

    def build_assets
      @item.build_actor_image if @item.actor_image.blank?
    end
  end
end

app/helpers/person_helper.rb
module PersonHelper
end

app/views/admin/people/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  header.content-header.js-content-header
    == render 'fae/shared/form_header', header: @klass_name
  == render 'fae/shared/errors'

  main.content
    = fae_input f, :name
    = fae_input f, :first_name
    = fae_input f, :last_name

    = fae_image_form f, :actor_image

    = fae_association f, :imdb

app/views/admin/people/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-column
    thead
      tr
        th Name
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to item.fae_display_field, edit_admin_person_path(item)
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found